### ISSUE TITLE
Add bp.json directly in Producer Report

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/bpvalidate#19]
<img width="528" alt="screen shot 2018-07-15 at 2 44 34 pm" src="https://user-images.githubusercontent.com/550895/42737077-b817f92c-883d-11e8-8915-46c885033644.png">

https://validate.eosnation.io/producers/eosnationftw.html

Easy access to bp.json directly from the BP report page

**Comment by matthewdarwin** [comment]
I added as a hyperlink within the body of the text... Hopefully that is ok for you...
