### ISSUE TITLE
allow multiple signing keys

### ISSUE THREAD

**Issue by notchxor** [EOS-Nation/bpvalidate#27]
allow multiples signing keys

**Comment by DenisCarriere** [comment]
@notchxor Can you elaborate? Is there a warning/info flag that is causing an issue or is the an extra validation check?

**Comment by notchxor** [comment]
yes, we need to put 2 or more signing keys in the bp.json, right now we have 2 producer_public_key wich is not optimal,
```
"producer_account_name": "argentinaeos",
"producer_public_key": "EOS7jq4FHrFrtCXxpRQ39dBeDMa5AjM4VaRbqBECkSa5aZnizJzrx",
"producer_public_key": "EOS7n4UUEDQRWeJ5UmCf9yqWXY5fsTtbo78HyYa5uBbM1xwa5DwRj",
```

**Comment by matthewdarwin** [comment]
I will add support for an array there.   producer_public_key: [ "EOS7jq4FHrFrtCXxpRQ39dBeDMa5AjM4VaRbqBECkSa5aZnizJzrx", "EOS7n4UUEDQRWeJ5UmCf9yqWXY5fsTtbo78HyYa5uBbM1xwa5DwRj"]

**Comment by n8d** [comment]
FYI there seems to be an agreement to remove the key from the standard, though it hasn't happened yet. It would be good to push that forward and remove the check here.

https://github.com/eosrio/bp-info-standard/issues/7

**Comment by matthewdarwin** [comment]
There is one use case where I know where having the key is useful. That is when someone steals a BP's identity entirely it is obvious if the key doesn't match.  This already happened.   (regproduce using an existing BP's URL).

**Comment by DenisCarriere** [comment]
I agree with @n8d to remove block signing key (more details https://github.com/eosrio/bp-info-standard/issues/7#issuecomment-409681518).

**Comment by matthewdarwin** [comment]
This check was removed a few weeks ago, so closing this issue since there seems to be no further comments.
