### ISSUE TITLE
duplicate peer for field isn't a valid test

### ISSUE THREAD

**Issue by HuweyII** [EOS-Nation/bpvalidate#29]
We are seeing this message on the tool, "duplicate peer for field=<node[1].p2p_endpoint> for host=<publicnode.cypherglass.com:9876>"

Have the same IP for all of our P2P and/or API endpoints is as designed because that IP points to a globally redundant anycast IP into a load balancing service.

**Comment by HuweyII** [comment]
Also applies to the error "duplicate URL for field"

i.e. 

  | Endpoints | duplicate URL for field=<node[1].api_endpoint> for url=<http://api.cypherglass.com>
-- | -- | --
  | Endpoints | duplicate URL for field=<node[1].ssl_endpoint> for url=<https://api.cypherglass.com>
  | Endpoints | duplicate peer for field=<node[1].p2p_endpoint> for host=<publicnode.cypherglass.com:9876>

**Comment by HuweyII** [comment]
Is this related to this error?  

  | Endpoints | no valid API endpoints provided for field=<node[1]> having node_type=<full>
-- | -- | --

Because that node does have valid endpoints.

` "nodes": [
    {
      "location": {
        "name": "Minneapolis, MN",
        "country": "US",
        "latitude": 44.989618,
        "longitude": -93.269376
      },
      "node_type": "full",
      "p2p_endpoint": "publicnode.cypherglass.com:9876",
      "api_endpoint": "http://api.cypherglass.com",
      "ssl_endpoint": "https://api.cypherglass.com"
    },
    {
      "location": {
        "name": "Kansas City, MO",
        "country": "US",
        "latitude": 39.099722,
        "longitude": -94.578333
      },
      "node_type": "full",
      "p2p_endpoint": "publicnode.cypherglass.com:9876",
      "api_endpoint": "http://api.cypherglass.com",
      "ssl_endpoint": "https://api.cypherglass.com"
    },
    {
      "location": {
        "name": "Kansas City, MO",
        "country": "US",
        "latitude": 39.099722,
        "longitude": -94.578333
      },
      "node_type": "producer",
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]`

**Comment by matthewdarwin** [comment]
The file seems a bit confusing because you are saying that the same end points physically exist in 2 different locations.  Clearly it is acceptable to have a load balancer or round-robin DNS that points over multiple locations.  

Would it work for you to avoid this document the endpoints only once with a location of "US" (which both Minneapolis and Kansas City)?  Then add the city names as empty nodes?   Or define the single location as "US: Minneapolis + Kansas City"?  (There is no validation on the content of the location field).

Other suggestions welcome.   The bpjson format is a bit awkward to work with.

**Comment by HuweyII** [comment]
My suggestion would be to remove this test, as I'm not sure it serves any purpose.

I tried what you suggested.  I still have this error, which might be a consequence?

Endpoints | no valid API endpoints provided for field=\<node[1]> having node_type=\<full>
-- | --

**Comment by matthewdarwin** [comment]
code is updated such that subsequent node sections of the same node_type can have no endpoints defined so as to accumulate locations for the previously defined endpoints.

However, the reports will just show the first location at this point.
