### ISSUE TITLE
mainnet-1.2.3 versioning

### ISSUE THREAD

**Issue by krypt007** [EOS-Nation/bpvalidate#33]
Hello,

After compiling mainnet -1.2.3 pull am getting version number c12d82b7 however the server on the validate page (https://github.com/EOS-Nation/bpvalidate/blob/master/config/versions.csv) for mainnet-1.2.3 is cb3645ae

**Comment by matthewdarwin** [comment]
cb3645ae https://validate.eosnation.io/reports/versions.html is the version number a lot of people have.   Are you certain you didn't make any other changes and you have exactly what is from mainnet repo?  "git status" should show no changes.

**Comment by matthewdarwin** [comment]
This problem will go away soon... we're going to use the version string that was introduced in v 1.2.0.
