### ISSUE TITLE
Warning flag for retrieving block_num 1

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/bpvalidate#39]
Fetching first block only applies for nodeos with full block synced, for nodes that use snapshots wouldn't have all blocks.

Shouldn't this be a warning and not an error?

> invalid block one, value=<400 Bad Request>, field=<node[0].api_endpoint>, having node_type=<full>, api_url=<http://api.moonxwitheos.com:8888/v1/chain/get_block>, post_data=<{"block_num_or_id": "1", "json": true}>

**Comment by matthewdarwin** [comment]
Correct... this is why the check is there. BP's API nodes should always have all the blocks, IMO.  Why do you think it is OK for API to not have them?
