### ISSUE TITLE
County code issue

### ISSUE THREAD

**Issue by EOS-Arabia** [EOS-Nation/bpvalidate#52]
Hello All

We are facing an issue related with our County code , we have set AE from http://www.nationsonline.org/oneworld/country_code_list.htm for United Arab Emirates

but we are still facing error in validator detection .
for more info kindly check 
https://validate.eosnation.io/eos/producers/eosarabianet.html
https://uae.eosarabia.net/bp.json

Regards,

**Comment by matthewdarwin** [comment]
You should set the location to 784 when you regproduce.

**Comment by EOS-Arabia** [comment]
it's fixed , thank you
