### ISSUE TITLE
Reports for Eostribe on Telos, Wax, Meetone.

### ISSUE THREAD

**Issue by yurakocyuba** [EOS-Nation/bpvalidate#55]
Hi!
Report contains "no valid HTTP or HTTPS API endpoints provided in any node; see above messages" although our bp.json provided such information.
Report for telos: https://validate.eosnation.io/telos/producers/eostribeprod.html
BP json for telos: https://eostribe.io/telos/bp.json

**Comment by matthewdarwin** [comment]
Please review the error messages in the report, like: 
```
db_size api is  enabled, value=<200 OK>, field=<node[0].api_endpoint>,  having node_type=<full>,  api_url=<http://api.meetone.eostribe.io/v1/db_size/get>
```
You should filter that API so it not publicly available.  (You can keep the plugin enabled, but change your load balancer to not allow public access to it).

**Comment by yurakocyuba** [comment]
> Please review the error messages in the report, like:
> 
> ```
> db_size api is  enabled, value=<200 OK>, field=<node[0].api_endpoint>,  having node_type=<full>,  api_url=<http://api.meetone.eostribe.io/v1/db_size/get>
> ```
> 
> You should filter that API so it not publicly available. (You can keep the plugin enabled, but change your load balancer to not allow public access to it).

I blocked that endpoint but nothing has changed
curl https://api.meetone.eostribe.io/v1/db_size/get
```
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>```

**Comment by matthewdarwin** [comment]
Looks ok now.  The validator was running behind schedule so it took longer than it should to update the report.
